name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_achievements: yes
          plugin_leetcode: yes
          plugin_leetcode_user: Virajjai
          plugin_codeforces: yes
          plugin_codeforces_user: Virajjai72
          config_timezone: Asia/Kolkata
          config_twemoji: yes
          config_display: large
          config_padding: 0
          config_mode: auto
